# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileconfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Protocol_Leds_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileconfig.proto',
  package='',
  serialized_pb=_b('\n\x10\x66ileconfig.proto\x1a\x13Protocol_Leds.proto\"\x1e\n\x0cTimingConfig\x12\x0e\n\x06period\x18\x01 \x02(\r\"U\n\nFileConfig\x12#\n\x0ctimingConfig\x18\x01 \x01(\x0b\x32\r.TimingConfig\x12\"\n\rrepLedsValues\x18\x02 \x03(\x0b\x32\x0b.LedsValues')
  ,
  dependencies=[Protocol_Leds_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMINGCONFIG = _descriptor.Descriptor(
  name='TimingConfig',
  full_name='TimingConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='period', full_name='TimingConfig.period', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=71,
)


_FILECONFIG = _descriptor.Descriptor(
  name='FileConfig',
  full_name='FileConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timingConfig', full_name='FileConfig.timingConfig', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repLedsValues', full_name='FileConfig.repLedsValues', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=158,
)

_FILECONFIG.fields_by_name['timingConfig'].message_type = _TIMINGCONFIG
_FILECONFIG.fields_by_name['repLedsValues'].message_type = Protocol_Leds_pb2._LEDSVALUES
DESCRIPTOR.message_types_by_name['TimingConfig'] = _TIMINGCONFIG
DESCRIPTOR.message_types_by_name['FileConfig'] = _FILECONFIG

TimingConfig = _reflection.GeneratedProtocolMessageType('TimingConfig', (_message.Message,), dict(
  DESCRIPTOR = _TIMINGCONFIG,
  __module__ = 'fileconfig_pb2'
  # @@protoc_insertion_point(class_scope:TimingConfig)
  ))
_sym_db.RegisterMessage(TimingConfig)

FileConfig = _reflection.GeneratedProtocolMessageType('FileConfig', (_message.Message,), dict(
  DESCRIPTOR = _FILECONFIG,
  __module__ = 'fileconfig_pb2'
  # @@protoc_insertion_point(class_scope:FileConfig)
  ))
_sym_db.RegisterMessage(FileConfig)


# @@protoc_insertion_point(module_scope)
