// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileconfig.proto

#ifndef PROTOBUF_fileconfig_2eproto__INCLUDED
#define PROTOBUF_fileconfig_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "Protocol_Leds.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_fileconfig_2eproto();
void protobuf_AssignDesc_fileconfig_2eproto();
void protobuf_ShutdownFile_fileconfig_2eproto();

class TimingConfig;
class FileConfig;

// ===================================================================

class TimingConfig : public ::google::protobuf::Message {
 public:
  TimingConfig();
  virtual ~TimingConfig();

  TimingConfig(const TimingConfig& from);

  inline TimingConfig& operator=(const TimingConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TimingConfig& default_instance();

  void Swap(TimingConfig* other);

  // implements Message ----------------------------------------------

  TimingConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TimingConfig& from);
  void MergeFrom(const TimingConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 period = 1;
  inline bool has_period() const;
  inline void clear_period();
  static const int kPeriodFieldNumber = 1;
  inline ::google::protobuf::uint32 period() const;
  inline void set_period(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:TimingConfig)
 private:
  inline void set_has_period();
  inline void clear_has_period();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 period_;
  friend void  protobuf_AddDesc_fileconfig_2eproto();
  friend void protobuf_AssignDesc_fileconfig_2eproto();
  friend void protobuf_ShutdownFile_fileconfig_2eproto();

  void InitAsDefaultInstance();
  static TimingConfig* default_instance_;
};
// -------------------------------------------------------------------

class FileConfig : public ::google::protobuf::Message {
 public:
  FileConfig();
  virtual ~FileConfig();

  FileConfig(const FileConfig& from);

  inline FileConfig& operator=(const FileConfig& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FileConfig& default_instance();

  void Swap(FileConfig* other);

  // implements Message ----------------------------------------------

  FileConfig* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FileConfig& from);
  void MergeFrom(const FileConfig& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .TimingConfig timingConfig = 1;
  inline bool has_timingconfig() const;
  inline void clear_timingconfig();
  static const int kTimingConfigFieldNumber = 1;
  inline const ::TimingConfig& timingconfig() const;
  inline ::TimingConfig* mutable_timingconfig();
  inline ::TimingConfig* release_timingconfig();
  inline void set_allocated_timingconfig(::TimingConfig* timingconfig);

  // repeated .LedsValues repLedsValues = 2;
  inline int repledsvalues_size() const;
  inline void clear_repledsvalues();
  static const int kRepLedsValuesFieldNumber = 2;
  inline const ::LedsValues& repledsvalues(int index) const;
  inline ::LedsValues* mutable_repledsvalues(int index);
  inline ::LedsValues* add_repledsvalues();
  inline const ::google::protobuf::RepeatedPtrField< ::LedsValues >&
      repledsvalues() const;
  inline ::google::protobuf::RepeatedPtrField< ::LedsValues >*
      mutable_repledsvalues();

  // @@protoc_insertion_point(class_scope:FileConfig)
 private:
  inline void set_has_timingconfig();
  inline void clear_has_timingconfig();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::TimingConfig* timingconfig_;
  ::google::protobuf::RepeatedPtrField< ::LedsValues > repledsvalues_;
  friend void  protobuf_AddDesc_fileconfig_2eproto();
  friend void protobuf_AssignDesc_fileconfig_2eproto();
  friend void protobuf_ShutdownFile_fileconfig_2eproto();

  void InitAsDefaultInstance();
  static FileConfig* default_instance_;
};
// ===================================================================


// ===================================================================

// TimingConfig

// required uint32 period = 1;
inline bool TimingConfig::has_period() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TimingConfig::set_has_period() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TimingConfig::clear_has_period() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TimingConfig::clear_period() {
  period_ = 0u;
  clear_has_period();
}
inline ::google::protobuf::uint32 TimingConfig::period() const {
  // @@protoc_insertion_point(field_get:TimingConfig.period)
  return period_;
}
inline void TimingConfig::set_period(::google::protobuf::uint32 value) {
  set_has_period();
  period_ = value;
  // @@protoc_insertion_point(field_set:TimingConfig.period)
}

// -------------------------------------------------------------------

// FileConfig

// optional .TimingConfig timingConfig = 1;
inline bool FileConfig::has_timingconfig() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FileConfig::set_has_timingconfig() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FileConfig::clear_has_timingconfig() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FileConfig::clear_timingconfig() {
  if (timingconfig_ != NULL) timingconfig_->::TimingConfig::Clear();
  clear_has_timingconfig();
}
inline const ::TimingConfig& FileConfig::timingconfig() const {
  // @@protoc_insertion_point(field_get:FileConfig.timingConfig)
  return timingconfig_ != NULL ? *timingconfig_ : *default_instance_->timingconfig_;
}
inline ::TimingConfig* FileConfig::mutable_timingconfig() {
  set_has_timingconfig();
  if (timingconfig_ == NULL) timingconfig_ = new ::TimingConfig;
  // @@protoc_insertion_point(field_mutable:FileConfig.timingConfig)
  return timingconfig_;
}
inline ::TimingConfig* FileConfig::release_timingconfig() {
  clear_has_timingconfig();
  ::TimingConfig* temp = timingconfig_;
  timingconfig_ = NULL;
  return temp;
}
inline void FileConfig::set_allocated_timingconfig(::TimingConfig* timingconfig) {
  delete timingconfig_;
  timingconfig_ = timingconfig;
  if (timingconfig) {
    set_has_timingconfig();
  } else {
    clear_has_timingconfig();
  }
  // @@protoc_insertion_point(field_set_allocated:FileConfig.timingConfig)
}

// repeated .LedsValues repLedsValues = 2;
inline int FileConfig::repledsvalues_size() const {
  return repledsvalues_.size();
}
inline void FileConfig::clear_repledsvalues() {
  repledsvalues_.Clear();
}
inline const ::LedsValues& FileConfig::repledsvalues(int index) const {
  // @@protoc_insertion_point(field_get:FileConfig.repLedsValues)
  return repledsvalues_.Get(index);
}
inline ::LedsValues* FileConfig::mutable_repledsvalues(int index) {
  // @@protoc_insertion_point(field_mutable:FileConfig.repLedsValues)
  return repledsvalues_.Mutable(index);
}
inline ::LedsValues* FileConfig::add_repledsvalues() {
  // @@protoc_insertion_point(field_add:FileConfig.repLedsValues)
  return repledsvalues_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::LedsValues >&
FileConfig::repledsvalues() const {
  // @@protoc_insertion_point(field_list:FileConfig.repLedsValues)
  return repledsvalues_;
}
inline ::google::protobuf::RepeatedPtrField< ::LedsValues >*
FileConfig::mutable_repledsvalues() {
  // @@protoc_insertion_point(field_mutable_list:FileConfig.repLedsValues)
  return &repledsvalues_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_fileconfig_2eproto__INCLUDED
